# Generated by Django 3.1.7 on 2021-03-26 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipe',
            fields=[
                ('receipe_name', models.CharField(max_length=300)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ingredients', models.CharField(max_length=270)),
                ('process', models.CharField(max_length=300)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
