# Generated by Django 3.1.7 on 2021-03-29 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recp', '0003_auto_20210328_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipe',
            old_name='image',
            new_name='images',
        ),
    ]
